service: apollo-lambda
plugins:
  - serverless-offline
  - serverless-bundle
  - serverless-dotenv-plugin
provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  environment:
    JWT_SECRET: "${env:JWT_SECRET}"
    GRAPH_CMS_API_TOKEN: "${env:GRAPH_CMS_API_TOKEN}"
    GRAPH_CMS_ENDPOINT: "${env:GRAPH_CMS_ENDPOINT}"
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: lambda.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
